version: '3'
networks:
  mynet:  #这里可以自定义名称 ，跟引用的地方一致就行
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  redroid:
    image: redroid/redroid:13.0.0_64only-latest
    container_name: redroid
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - 5555:5555
    volumes:
      - /data/redroid/dev_fs:/data
    command:
      - ro.secure=0 # 允许 ADB Root 调试
    networks:
      mynet:
        ipv4_address: 172.18.0.254