version: '3'
networks:
  mynet:  #这里可以自定义名称 ，跟引用的地方一致就行
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  redroid:
    image: registry.cn-guangzhou.aliyuncs.com/xuchen/redroid:1.0
    container_name: redroid
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - 5555:5555
    volumes:
      - /data/redroid/dev_fs:/data
    command:
      - ro.secure=0 # 允许 ADB Root 调试
      - ro.product.cpu.abilist=x86_64,arm64-v8a,x86,armeabi-v7a,armeabi
      - ro.product.cpu.abilist64=x86_64,arm64-v8a
      - ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
      - ro.dalvik.vm.isa.arm=x86
      - ro.dalvik.vm.isa.arm64=x86_64
      - ro.enable.native.bridge.exec=1
      - ro.dalvik.vm.native.bridge=libndk_translation.so
      - ro.ndk_translation.version=0.2.2
      - ro.kernel.qemu.wifi=1
      - androidboot.redroid_net_ndns=2
      - androidboot.redroid_net_dns1=223.5.5.5
      - androidboot.redroid_net_dns2=223.6.6.6
    networks:
      mynet:
        ipv4_address: 172.18.0.254