version: '3'
networks:
  mynet:  #这里可以自定义名称 ，跟引用的地方一致就行
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  redroid: #安卓仿真机器  ，https://blog.csdn.net/u012960155/article/details/129277193
    image: redroid/redroid:13.0.0_64only-latest
    container_name: redroid
    privileged: true
    restart: always
    stdin_open: true
    ports:
      - "5555:5555"
    volumes:
      - /data/redroid/dev_fs:/data
    command:
      - androidboot.redroid_gpu_mode=host
      - ro.product.cpu.abilist=x86_64,arm64-v8a,x86,armeabi-v7a,armeabi
      - ro.product.cpu.abilist64=x86_64,arm64-v8a
      - ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
      - ro.dalvik.vm.isa.arm=x86
      - ro.dalvik.vm.isa.arm64=x86_64
      - ro.enable.native.bridge.exec=1
      - ro.dalvik.vm.native.bridge=libndk_translation.so
      - ro.ndk_translation.version=0.2.2
      - ro.secure=0 # 允许 ADB Root 调试
    networks:
      mynet:
        ipv4_address: 172.18.0.254