version: '3'
networks:
  mynet:  #这里可以自定义名称 ，跟引用的地方一致就行
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./log/mysql/:/var/log/mysql/:rw
      - ./data/mysql/data/:/var/lib/mysql/:rw
      - ./data/mysql/mysql-files/:/var/lib/mysql-files:rw
    command:
      --default-authentication-plugin=mysql_native_password
      --innodb-flush-method=O_DSYNC
      --innodb-use-native-aio=0
      --log_bin=ON
    container_name: mysql
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      mynet:
        ipv4_address: 172.18.0.105

  nacos01:
    image: nacos/nacos-server:v2.2.3-slim
    ports:
      - "8848:8848"
    container_name: nacos01
    restart: always
    volumes:
      - ./log/nacos/logs:/home/nacos/logs
    environment:
      PREFER_HOST_MODE: ip
      MODE: cluster
      NACOS_SERVER_IP: 172.18.0.131
      NACOS_SERVERS: "172.18.0.131:8848 172.18.0.132:8848 172.18.0.133:8848"
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 172.18.0.105
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      JVM_XMS: 256m
      JVM_XMX: 512m
      JVM_XMN: 256m
    depends_on:
      - mysql
    networks:
      mynet:
        ipv4_address: 172.18.0.131

  nacos02:
    image: nacos/nacos-server:v2.2.3-slim
    ports:
      - "8849:8848"
    container_name: nacos02
    restart: always
    volumes:
      - ./log/nacos/logs:/home/nacos/logs
    environment:
      PREFER_HOST_MODE: ip
      MODE: cluster
      NACOS_SERVER_IP: 172.18.0.132
      NACOS_SERVERS: "172.18.0.131:8848 172.18.0.132:8848 172.18.0.133:8848"
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 172.18.0.105
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      JVM_XMS: 256m
      JVM_XMX: 512m
      JVM_XMN: 256m
    depends_on:
      - mysql
    networks:
      mynet:
        ipv4_address: 172.18.0.132

  nacos03:
    image: nacos/nacos-server:v2.2.3-slim
    ports:
      - "8850:8848"
    container_name: nacos03
    restart: always
    volumes:
      - ./log/nacos/logs:/home/nacos/logs
    environment:
      PREFER_HOST_MODE: ip
      MODE: cluster
      NACOS_SERVER_IP: 172.18.0.133
      NACOS_SERVERS: "172.18.0.131:8848 172.18.0.132:8848 172.18.0.133:8848"
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 172.18.0.105
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      JVM_XMS: 256m
      JVM_XMX: 512m
      JVM_XMN: 256m
    depends_on:
      - mysql
    networks:
      mynet:
        ipv4_address: 172.18.0.133