version: '2'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    restart: always
    container_name: nginx
    links:
      - php72:fpm72
      - php56:fpm56
      - php70:fpm70

  php72:
    #build: ./php/php72/
    image: registry.cn-hangzhou.aliyuncs.com/xuchen/php:7.2
    expose:
      - 9000
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    restart: always
    container_name: php72
    privileged: true
    links:
      - redis:redis
      - memcached:memcached
#      - mysql:mysql

  php70:
    image: registry.cn-hangzhou.aliyuncs.com/xuchen/php:7.0
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    restart: always
    container_name: php70
    privileged: true
    links:
      - redis:redis
      - memcached:memcached
#      - mysql:mysql

  php56:
    #build: ./php/php56/
    image: registry.cn-hangzhou.aliyuncs.com/xuchen/php:5.6
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    restart: always
    container_name: php56
    privileged: true
    links:
      - redis:redis
      - memcached:memcached
#      - mysql:mysql



  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    container_name: redis

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    restart: always
    container_name: memcached

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./data/mysql/:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb/:/data/db/:rw
    restart: always
    command: mongod --smallfiles --logpath=/dev/null #windows挂载报错解决方案

  etcd:
    build: ./etcd/
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
      - "7001:7001"
    volumes:
      - ./data/etcd/:/data/:rw
    container_name: etcd



#  rabbitmq:
#    image: rabbitmq:3.7-alpine
#    ports:
#          - "5762:5762" #client端
#          - "15672:15672" #web管理端
#          - "25672:25672" #server端口
#          - "4369:4369" #erlang发现口
#    container_name: rabbitmq
#    environment:
#      RABBITMQ_DEFAULT_USER: root
#      RABBITMQ_DEFAULT_PASS: 123456
#zookeeper
#  zoo1:
#    image: zookeeper:latest
#    container_name: zoo1
#    restart: always
#    hostname: zoo1
#    ports:
#      - 2181:2181
#    volumes:
#      - ./data/zookeeper/:/data/zookeeper/:rw
#      - ./log/zookeeper/:/var/log/zookeeper/:rw
#    environment:
#      ZOO_MY_ID: 1
#      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
#
#  zoo2:
#    image: zookeeper:latest
#    container_name: zoo2
#    restart: always
#    hostname: zoo2
#    ports:
#      - 2182:2181
#    volumes:
#        - ./data/zookeeper/:/data/zookeeper/:rw
#        - ./log/zookeeper/:/var/log/zookeeper/:rw
#    environment:
#      ZOO_MY_ID: 2
#      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
#
#  zoo3:
#    image: zookeeper:latest
#    container_name: zoo3
#    restart: always
#    hostname: zoo3
#    ports:
#      - 2183:2181
#    volumes:
#        - ./data/zookeeper/:/data/zookeeper/:rw
#        - ./log/zookeeper/:/var/log/zookeeper/:rw
#    environment:
#      ZOO_MY_ID: 3
#      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888

  elasticsearch:
    image: elasticsearch:5.6.12-alpine
    container_name: es
    ports:
      - 9200:9200
      - 9300:9300


#  kibana:
#    image: kibana:latest
#    container_name: kibana
#    ports:
#      - 5601:5601
