version: '2'
services:
  centos:
    image: centos
    ports:
      - 7890:7890
    volumes:
      - ./www/:/var/www/html/:rw
    container_name: linux
    privileged: true
    networks:
      game:
        ipv4_address: 192.168.1.111

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/
    container_name: nginx
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    networks:
      game:
        ipv4_address: 192.168.1.3



  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./data/mysql/:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      game:
        ipv4_address: 192.168.1.2



networks:
  game:  #这里可以自定义名称 ，跟引用的地方一致就行
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1