version: '3.7'
networks:
  jhm:  #这里可以自定义名称 ，跟引用的地方一致就行
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www/:/var/www/html/:delegated
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:cached
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./log/nginx/:/var/log/nginx/:delegated
    container_name: nginx
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    networks:
      jhm:
        ipv4_address: 172.18.0.50

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis
    command: redis-server --requirepass 123456
    networks:
      jhm:
        ipv4_address: 172.18.0.100
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 10M
        reservations:
          cpus: '0.25'
          memory: 2M

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    container_name: memcached
    networks:
      jhm:
        ipv4_address: 172.18.0.101
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 10M
        reservations:
          cpus: '0.25'
          memory: 2M

  php72:
    image: registry.cn-hangzhou.aliyuncs.com/xuchen/php:7.2
    expose:
      - 9000
    volumes:
      - ./www/:/var/www/html/:delegated
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
      - ./log/php-fpm/:/var/log/php-fpm/:delegated
    container_name: php72
    extra_hosts:
      - "hddev.kerlala.com:172.18.0.50"
    privileged: true
    networks:
      jhm:
        ipv4_address: 172.18.0.72
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 50M