version: '3.0'
networks:
  mynet:  #这里可以自定义名称 ，跟引用的地方一致就行
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24


services:
  nginx:
    image: registry.cn-guangzhou.aliyuncs.com/xuchen/proxy:nginx-alpine
    ports:
      - "80:80"
      - "443:443"
#      - "1234:1234" #nacos http端口
#      - "2234:2234" #nacos grpc端口
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx/:/var/log/nginx/
    container_name: nginx
    privileged: true
    extra_hosts:
      - "casdev.kerlala.com:127.0.0.1"
      - "hdcrmdev.kerlala.com:127.0.0.1"
      - "jxjkhddev.kerlala.com:127.0.0.1"
      - "jxjkhdcrmdev.kerlala.com:127.0.0.1"
      
      - "jxjkhdcrmbch.kerlala.com:182.92.3.164"
      - "jxjkhdbch.kerlala.com:182.92.3.164"
      - "resbch.kerlala.com:182.92.3.164"
      - "ccbresbch.kerlala.com:182.92.3.164"
      - "h5bch.kerlala.com:182.92.3.164"
      - "scrmbch.kerlala.com:182.92.3.164"
      - "scrmresbch.kerlala.com:182.92.3.164"
    networks:
      mynet:
        ipv4_address: 172.18.0.2

  redis:
    image: registry.cn-guangzhou.aliyuncs.com/xuchen/proxy:redis-alpine
    ports:
      - "6379:6379"
    container_name: redis
    command: redis-server --requirepass 123456
    networks:
      mynet:
        ipv4_address: 172.18.0.100

  mysql-master:
   image: registry.cn-guangzhou.aliyuncs.com/xuchen/proxy:mysql-8.0
   ports:
     - "3306:3306"
   volumes:
     - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
     - ./log/mysql/:/var/log/mysql/:rw
     - ./data/mysql/data/:/var/lib/mysql/:rw
     - ./data/mysql/mysql-files/:/var/lib/mysql-files:rw
   command: >
     --server-id=1
     --default-authentication-plugin=mysql_native_password
     --innodb-flush-method=O_DSYNC
     --innodb-use-native-aio=0
     --log_bin=ON
   container_name: mysql_master
   privileged: true
   environment:
     MYSQL_ROOT_PASSWORD: 123456
     MYSQL_REPLICATION_MODE: master
     MYSQL_REPLICATION_USER: abner  #主从同步的用户
     MYSQL_REPLICATION_PASSWORD: abner
   networks:
     mynet:
       ipv4_address: 172.18.0.102

  mysql-slave:
   image: registry.cn-guangzhou.aliyuncs.com/xuchen/proxy:mysql-8.0
   ports:
     - "3307:3306"
   volumes:
     - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
     - ./log/mysql/:/var/log/mysql/:rw
     - ./data/mysql/data/:/var/lib/mysql/:rw
     - ./data/mysql/mysql-files/:/var/lib/mysql-files:rw
   command:
     --server-id=2
     --read-only=1
     --default-authentication-plugin=mysql_native_password
     --innodb-flush-method=O_DSYNC
     --innodb-use-native-aio=0
     --log_bin=ON
   container_name: mysql_slave
   privileged: true
   environment:
     MYSQL_ROOT_PASSWORD: 123456
     MYSQL_REPLICATION_MODE: slave
     MYSQL_REPLICATION_USER: abner
     MYSQL_REPLICATION_PASSWORD: abner
   depends_on:
     - mysql-master
   networks:
     mynet:
       ipv4_address: 172.18.0.103

  php82:
    image: registry.cn-guangzhou.aliyuncs.com/xuchen/php:8.2
    expose:
      - 9000
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./log/php-fpm/:/var/log/php-fpm/
    container_name: php82
    privileged: true
    extra_hosts:
      - "hddev.kerlala.com:172.18.0.2"
      - "jxjkhddev.kerlala.com:172.18.0.2"
      - "jxjkhdcrmdev.kerlala.com:172.18.0.2"
      - "mockdev.kerlala.com:172.18.0.2"
      - "casdev.kerlala.com:172.18.0.2"
    networks:
      mynet:
        ipv4_address: 172.18.0.82

#  vuecli:
#   image: registry.cn-guangzhou.aliyuncs.com/xuchen/node:1.0
#   tty: true
#   ports:
#     - '8081:8081'
#     - '4000:4000'
#   volumes:
#     - '/Users/abner/work/gopro/govue/front:/app/front'
#     - '/Users/abner/work/blog:/app/blog'
#     - '/Users/abner/work/nopro:/app/nopro'
#     - '/Users/abner/.ssh:/root/.ssh'
#   container_name: vuecli
#   networks:
#     mynet:
#       ipv4_address: 172.18.0.10

