version: '3.1'
networks:
  jhm:  #这里可以自定义名称 ，跟引用的地方一致就行
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx/:/var/log/nginx/
    container_name: nginx
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    networks:
      jhm:
        ipv4_address: 172.18.0.50


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis
    command: redis-server --requirepass 123456
    networks:
      jhm:
        ipv4_address: 172.18.0.100


  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    container_name: memcached
    networks:
      jhm:
        ipv4_address: 172.18.0.101


  php74:
    image: registry.cn-guangzhou.aliyuncs.com/xuchen/php:7.4
    expose:
      - 9000
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./log/php-fpm/:/var/log/php-fpm/
    container_name: php74
    privileged: true
    dns:
      - "114.114.114.114"
      - "8.8.8.8"
    extra_hosts:
      - "hddev.kerlala.com:172.18.0.50"
      - "ccbhddev.kerlala.com:172.18.0.50"
    networks:
      jhm:
        ipv4_address: 172.18.0.74

  node:
   image: registry.cn-guangzhou.aliyuncs.com/xuchen/node:1.0
   ports:
     - 4000:4000
   volumes:
     - /Users/abner/work/nodepro:/app:rw
     - /Users/abner/.ssh:/root/.ssh/:rw
   container_name: app
   privileged: true
   stdin_open: true # 加上不自动退出 ，打开一个可输入的终端
   tty: true # 加上不自动退出，打开一个模拟终端，docker run -it(这个t)
   extra_hosts:
     - "raw.githubusercontent.com:199.232.68.133"
     - "user-images.githubusercontent.com:199.232.68.133"
   networks:
     jhm:
       ipv4_address: 172.18.0.102


  mysql:
    image: mysql:5.7.31
    container_name: mysql
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql/:/var/lib/mysql/
      - ./data/mysql/:/usr/data/:rw
      - ./log/mysql/:/var/log/mysql/:rw
    environment:
       MYSQL_ROOT_PASSWORD: 123456
    user: "1000:50"
#    command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON
    networks:
      jhm:
        ipv4_address: 172.18.0.110

#  php56:
#   image: registry.cn-hangzhou.aliyuncs.com/xuchen/php:5.6
#   expose:
#     - 9000
#   volumes:
#     - ./www/:/var/www/html/
#     - ./conf/php/php.ini:/usr/local/etc/php/php.ini
#     - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
#     - ./log/php-fpm/:/var/log/php-fpm/
#   container_name: php56
#   privileged: true
#   networks:
#     jhm:
#         ipv4_address: 172.18.0.56