version: '3.1' #mysql集群测试
networks:
  jhm:  #这里可以自定义名称 ，跟引用的地方一致就行
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24

services:
  mysql_w:
      image: mysql:5.6.45
      container_name: mysql_w
      privileged: true
      ports:
        - "13306:3306"
      command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON #解决windows挂载无法启动
      environment:
         MYSQL_ROOT_PASSWORD: 123456
      networks:
        jhm:
          ipv4_address: 172.18.0.10

  mysql_r:
      image: mysql:5.6.45
      container_name: mysql_r
      privileged: true
      ports:
        - "13307:3306"
      command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON #解决windows挂载无法启动
      environment:
         MYSQL_ROOT_PASSWORD: 123456
      networks:
        jhm:
          ipv4_address: 172.18.0.11

  ac_w:
      image: mysql:5.6.45
      container_name: ac_w
      privileged: true
      ports:
        - "23306:3306"
      command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON #解决windows挂载无法启动
      environment:
         MYSQL_ROOT_PASSWORD: 123456
      networks:
        jhm:
          ipv4_address: 172.18.0.12

  ac_r:
      image: mysql:5.6.45
      container_name: ac_r
      privileged: true
      ports:
        - "23307:3306"
      command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON #解决windows挂载无法启动
      environment:
         MYSQL_ROOT_PASSWORD: 123456
      networks:
        jhm:
          ipv4_address: 172.18.0.13
