version: '2'
#ip[nginx=...2,php56=....56,php72=....72]

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/
    container_name: nginx
    privileged: true
    networks:
      default:
        ipv4_address: 172.18.0.50

  php72:
    image: registry.cn-hangzhou.aliyuncs.com/xuchen/php:7.2
    expose:
      - 9000
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
      - ./log/ekt/:/var/log/ekt/:rw #ztth log
    container_name: php72
    privileged: true
    links:
          - redis:redis
          - memcached:memcached
#          - mysql:mysql
    extra_hosts:
      - "e-ticket-dzcx-dev.icsoc.net:172.18.0.50"
      - "dzcx-dev.icsoc.net:172.18.0.50"
    networks:
      default:
        ipv4_address: 172.18.0.72


  php56:
    #build: ./php/php56/
    image: registry.cn-hangzhou.aliyuncs.com/xuchen/php:5.6
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
      - ./log/ekt/:/var/log/ekt/:rw #ztth log
    container_name: php56
    privileged: true
    links:
      - redis:redis
      - memcached:memcached
#      - mysql:mysql
    extra_hosts:
      - "e-ticket-dzcx-dev.icsoc.net:172.18.0.50"
      - "dzcx-dev.icsoc.net:172.18.0.50"
    networks:
      default:
        ipv4_address: 172.18.0.56



  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    container_name: memcached

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./data/mysql/:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb/:/data/db/:rw
    command: mongod --smallfiles --logpath=/dev/null #windows挂载报错解决方案


networks:
  default:  #这里可以自定义名称 ，跟引用的地方一致就行
    ipam:
      config:
        - subnet: 172.18.0.0/24
        - gateway: 172.18.0.1